[module/workspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true
enable-scroll = true
format = <label-state>
label-active = ❤
label-active-foreground = ${color.primary}
label-active-background = ${color.background}
label-active-padding = 2
label-occupied = ●
label-occupied-foreground = ${color.forground}
label-occupied-padding = 2
label-urgent = ⚠
label-urgent-foreground = ${color.secondary}
label-urgent-padding = 2
label-empty = ○
label-empty-foreground = ${color.foreground-alt}
label-empty-padding = 2

[module/quote]
type = custom/script
exec = ~/.config/polybar/OurBar/music_or_quote.sh
interval = 3
format = <label>
label =   %output%
label-foreground = ${color.primary}

# If music is up, click pauses it. If quote is up, click tells you the source and shuffles a new quote!
click-left = playerctl play-pause 2>/dev/null || (~/.config/polybar/OurBar/quote-source.sh && ~/.config/polybar/OurBar/quotes.sh)

[module/quote-timer]
type = custom/script
exec = ~/.config/polybar/OurBar/quotes.sh
interval = 300

[module/gap]
type = custom/text
content = |



[module/date]
type = internal/date
interval = 1.0
date = %a %d %b
time = %I:%M %p
format = <label>
label = %time%  %date%
label-foreground = ${color.primary}

[module/volume]
type = internal/pulseaudio
use-ui-max = false
interval = 5
format-volume = <ramp-volume>  <label-volume>
format-volume-prefix = " "
format-muted = <label-muted>
format-muted-prefix = " "
label-volume = %percentage%%
label-volume-foreground = ${color.primary}
label-muted =  Muted
label-muted-foreground = ${color.foreground-alt}
ramp-volume-0 =  
ramp-volume-0-foreground = ${color.primary}
ramp-volume-1 =  
ramp-volume-1-foreground = ${color.primary}
ramp-volume-2 =  
ramp-volume-2-foreground = ${color.primary}

[module/network]
type = internal/network
interface-type = wired

interval = 1.0

accumulate-stats = true

unknown-as-up = true

format-connected = <label-connected>
format-connected-prefix = 

format-disconnected = <label-disconnected>
format-disconnected-prefix = 

label-connected = "%{A1:networkmanager_dmenu &:} 󰖩  Connected%{A}"
label-connected-foreground = ${color.primary}

label-disconnected = "%{A1:networkmanager_dmenu &:}󰖪 Disconnected%{A}"
label-disconnected-foreground = ${color.foreground-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
