#!/usr/bin/env bash

QUOTES=(
  "NO COST TOO GREAT"
  "Wake the f*** up, Samurai"
  "The cake is a lie"
  "Would you kindly"
  "War. War never changes"
  "Stay awhile and listen"
  "It's dangerous to go alone"
  "Do a barrel roll"
  "Hadouken"
  "All your base are belong to us"
  "A man chooses, a slave obeys"
  "The right man in the wrong place"
  "I used to be an adventurer like you"
  "What is a man? A miserable little pile of secrets"
  "Rise and shine, Mr. Freeman"
  "Finish the fight"
  "We all make choices, but in the end our choices make us"
  "Za Warudo"
  "I'll be back"
  "Go ahead, make my day"
  "I see dead people"
  "To infinity and beyond"
  "Just keep swimming"
  "There's no place like home"
  "May the Force be with you"
  "I am your father"
  "With great power comes great responsibility"
  "Why so serious"
  "You shall not pass"
  "This is Sparta"
  "The precious"
  "I solemnly swear that I am up to no good"
  "After all this time? Always"
  "Not all those who wander are lost"
  "Speak friend and enter"
  "Power overwhelming"
  "Gott ist tot"
  "You are already dead"
  "Omae wa mou shindeiru"
  "Nothing happened, nothing is happening"
  "I am the bone of my sword"
  "People die when they are killed"
  "The world is not beautiful, therefore it is"
  "We live in a society"
  "ZOLTRAAK"
  "When I die I return to my save point"
  "I call it return by death"
  "LET ME TELL YOU HOW MUCH I CAME TO HATE YOU"
  "But nobody came"
  "FOR 4 MINUTES AND ELEVEN SECONDS HAKARI WAS EFFICIENTLY IMMORTAL"
  "Love is the most cursed thing"
  "except satoru gojo of course"
  "I came, I saw, I conquered"
)

SOURCES=(
  "Hollow Knight"
  "Cyberpunk 2077"
  "Portal"
  "Bioshock"
  "Fallout"
  "Diablo"
  "The Legend of Zelda"
  "Star Fox 64"
  "Street Fighter"
  "Zero Wing"
  "Bioshock"
  "Skyrim"
  "Skyrim"
  "Castlevania: Symphony of the Night"
  "Half-Life 2"
  "Halo 3"
  "BioShock"
  "JoJo's Bizarre Adventure"
  "The Terminator"
  "Sudden Impact / Dirty Harry"
  "The Sixth Sense"
  "Toy Story"
  "Finding Nemo"
  "The Wizard of Oz"
  "Star Wars"
  "Star Wars: The Empire Strikes Back"
  "Spider-Man"
  "The Dark Knight"
  "The Lord of the Rings"
  "300"
  "The Lord of the Rings"
  "Harry Potter"
  "Harry Potter and the Deathly Hallows"
  "The Lord of the Rings"
  "The Lord of the Rings"
  "StarCraft (cheat code)"
  "Madoka Magica: Rebellion"
  "Fist of the North Star"
  "Fist of the North Star"
  "One Piece (Zoro)"
  "Fate/stay night"
  "Fate/stay night"
  "Kino's Journey"
  "Joker meme / Zack Snyder's Justice League"
  "Frieren"
  "Re:Zero"
  "Re:Zero"
  "I Have No Mouth, and I Must Scream"
  "Undertale"
  "Jujutsu Kaisen"
  "Jujutsu Kaisen 0"
  "Jujutsu Kaisen"
  "Julius Caesar"
)

CACHE="$HOME/.cache/polybar-quote"

RANDOM_INDEX=$(( RANDOM % ${#QUOTES[@]} ))
echo "${QUOTES[$RANDOM_INDEX]}"
echo "${SOURCES[$RANDOM_INDEX]}" > "$CACHE"
